const now = new Date().toISOString()

// bump this version to force-reset localStorage on next load
export const SEED_VERSION = '2026-02-27-v6'

export const SEED_TASKS = [
  // ======= AHMAD =======
  {
    id: 'a1',
    title: 'Build AI Agent - Technical Proposal System',
    description: 'بناء AI Agent لإنشاء Technical Proposals تلقائياً لعملاء Audiom',
    assignee: 'Ahmad',
    priority: 'high',
    status: 'inprogress',
    tags: ['Audiom', 'AI'],
    dueDate: '2026-03-05',
    createdAt: now,
  },
  {
    id: 'a2',
    title: 'Domain Setup + Webflow for audiom.sa',
    description: 'ضبط الدومين وربطه مع Webflow لموقع audiom.sa',
    assignee: 'Ahmad',
    priority: 'medium',
    status: 'inprogress',
    tags: ['Audiom', 'Webflow'],
    dueDate: '2026-03-10',
    createdAt: now,
  },
  {
    id: 's1',
    title: 'Follow Up with Tech Team (Sonika)',
    description: 'متابعة أحمد حجازي + مصطفى — الموعد الخميس 6 مارس',
    assignee: 'Ahmad',
    priority: 'high',
    status: 'todo',
    tags: ['Sonika'],
    dueDate: '2026-03-06',
    createdAt: now,
  },
  {
    id: 's2',
    title: 'Review MVP Platform Requirements (Sonika)',
    description: 'مراجعة متطلبات الـ MVP قبل اجتماع الفريق التقني القادم',
    assignee: 'Ahmad',
    priority: 'high',
    status: 'todo',
    tags: ['Sonika', 'MVP'],
    dueDate: '2026-03-06',
    createdAt: now,
  },
  {
    id: 'a3',
    title: 'Benderz — Make a Decision',
    description: 'قرار نهائي: هل نكمل مشروع Benderz أو نوقفه رسمياً؟',
    assignee: 'Ahmad',
    priority: 'medium',
    status: 'todo',
    tags: ['Audiom', 'Benderz'],
    dueDate: '2026-03-15',
    createdAt: now,
  },
  {
    id: 'a4',
    title: 'Plan AI Automation Roadmap (Audiom)',
    description: 'وضع خارطة طريق واضحة لمشاريع الأتمتة داخل Audiom',
    assignee: 'Ahmad',
    priority: 'medium',
    status: 'todo',
    tags: ['Audiom', 'AI', 'Planning'],
    createdAt: now,
  },
  {
    id: 'a5',
    title: 'Webhook → n8n Integration',
    description: 'ربط OpenClaw بـ n8n عبر HTTP webhook — لما يصل trigger من n8n ينبّه دانا فوراً',
    assignee: 'Ahmad',
    priority: 'medium',
    status: 'todo',
    tags: ['n8n', 'Integration', 'Automation'],
    dueDate: '2026-03-20',
    createdAt: now,
  },
  {
    id: 'a6',
    title: 'Ramz — Automation Proposal (Daily Campaign Report)',
    description: 'اقتراح أتمتة لمشروع رمز: تقرير يومي تلقائي للحملات — بانتظار قرارهم',
    assignee: 'Ahmad',
    priority: 'medium',
    status: 'todo',
    tags: ['Ramz', 'Audiom', 'Automation'],
    createdAt: now,
  },

  // ======= DANA =======
  {
    id: 'd-vercel',
    title: 'Deploy Mission Control to Vercel',
    description: 'نشر التطبيق على Vercel — متاح من أي جهاز أو جوال بدون نفس الـ WiFi',
    assignee: 'Dana',
    priority: 'medium',
    status: 'todo',
    tags: ['Mission Control', 'Deployment'],
    dueDate: '2026-03-12',
    createdAt: now,
  },
  // --- مكتمل ---
  {
    id: 'd-done1',
    title: 'Heartbeat System — Escalation & Improvements',
    description: 'تحسين نظام الـ Heartbeat: مستويات تنبيه (🟡🔴)، TTS للعاجل، morning escalation، alerts.md',
    assignee: 'Dana',
    priority: 'high',
    status: 'done',
    tags: ['OpenClaw', 'Heartbeat', 'Automation'],
    createdAt: now,
  },
  {
    id: 'd-done2',
    title: 'session-memory Hook — Enable',
    description: 'تفعيل session-memory hook — يحفظ السياق تلقائياً عند /new أو /reset',
    assignee: 'Dana',
    priority: 'medium',
    status: 'done',
    tags: ['OpenClaw', 'Memory'],
    createdAt: now,
  },
  {
    id: 'd-done3',
    title: 'activeHours — Configure Heartbeat',
    description: 'ضبط ساعات عمل الـ Heartbeat: 8 صباحاً → 11 مساءً فقط',
    assignee: 'Dana',
    priority: 'medium',
    status: 'done',
    tags: ['OpenClaw', 'Heartbeat'],
    createdAt: now,
  },
  {
    id: 'd-done4',
    title: 'OpenClaw Update — v2026.2.26',
    description: 'تحديث OpenClaw من 2026.2.25 إلى 2026.2.26 — Root cause: vec0.dll lock. Fix: إيقاف Gateway task أولاً',
    assignee: 'Dana',
    priority: 'high',
    status: 'done',
    tags: ['OpenClaw', 'صيانة'],
    createdAt: now,
  },
  {
    id: 'd-done5',
    title: 'Watchdog System — Fix & Verify',
    description: 'إعادة كتابة watchdog.ps1 مع logging + اختبار live (gateway killed → watchdog restarted خلال 5 دقايق)',
    assignee: 'Dana',
    priority: 'high',
    status: 'done',
    tags: ['OpenClaw', 'صيانة'],
    createdAt: now,
  },
  {
    id: 'd-done6',
    title: 'System Healthcheck — Full Audit',
    description: 'فحص شامل: OS، Firewall، BitLocker، Ports، HiviewService، OpenClaw security — كل شيء pass',
    assignee: 'Dana',
    priority: 'medium',
    status: 'done',
    tags: ['صيانة', 'أمان'],
    createdAt: now,
  },
  {
    id: 'd-done7',
    title: 'Audiom Onboarding — Full Context',
    description: 'استيعاب كامل لـ Audiom: خدمات، عملاء، workflows، 19 PDF مستخرجة — audiom-context.md محفوظ',
    assignee: 'Dana',
    priority: 'medium',
    status: 'done',
    tags: ['Audiom', 'Memory'],
    createdAt: now,
  },
  {
    id: 'd-done8',
    title: 'Mission Control — Mobile Friendly',
    description: 'تحديث الداشبورد للموبايل: stats 2x2، columns تتكدس، bottom sheet modal، touch targets أكبر',
    assignee: 'Dana',
    priority: 'medium',
    status: 'done',
    tags: ['Mission Control', 'UI'],
    createdAt: now,
  },

  // --- نشط ---
  {
    id: 'd7',
    title: 'Setup Browser & Internet Access Tools',
    description: 'تثبيت وتفعيل Browser Relay + X login + extensions مطلوبة',
    assignee: 'Dana',
    priority: 'high',
    status: 'inprogress',
    tags: ['Setup', 'Browser', 'Tools'],
    createdAt: now,
  },

  // --- قائمة ---
  {
    id: 'd1',
    title: 'Mission Control — Memory Viewer Screen',
    description: 'شاشة تعرض ملفات الذاكرة بـ UI جميل مع بحث',
    assignee: 'Dana',
    priority: 'medium',
    status: 'todo',
    tags: ['Mission Control'],
    createdAt: now,
  },
  {
    id: 'd2',
    title: 'Google Calendar Integration',
    description: 'ربط Google Calendar لإدارة مواعيد أحمد وجدولة المهام تلقائياً',
    assignee: 'Dana',
    priority: 'medium',
    status: 'todo',
    tags: ['Integration', 'Google'],
    dueDate: '2026-03-18',
    createdAt: now,
  },
  {
    id: 'd3',
    title: 'Mission Control — Content Pipeline Screen',
    description: 'شاشة إدارة المحتوى: فكرة → سكريبت → تصوير',
    assignee: 'Dana',
    priority: 'medium',
    status: 'todo',
    tags: ['Mission Control', 'Content'],
    createdAt: now,
  },
  {
    id: 'd4',
    title: 'Mission Control — Team Screen',
    description: 'شاشة عرض الـ Sub-agents بأدوار واضحة',
    assignee: 'Dana',
    priority: 'medium',
    status: 'todo',
    tags: ['Mission Control', 'Agents'],
    createdAt: now,
  },
  {
    id: 'd5',
    title: 'Setup X Account in Browser',
    description: 'تسجيل دخول @Dana_persists في المتصفح',
    assignee: 'Dana',
    priority: 'low',
    status: 'todo',
    tags: ['Setup', 'X'],
    createdAt: now,
  },
  {
    id: 'd6',
    title: 'Explore n8n Integration',
    description: 'ربط n8n بـ OpenClaw لتشغيل Workflows مباشرة',
    assignee: 'Dana',
    priority: 'medium',
    status: 'todo',
    tags: ['n8n', 'Integration', 'Automation'],
    createdAt: now,
  },
  {
    id: 'd8',
    title: 'Setup Tailscale — Remote Access',
    description: 'تثبيت Tailscale على الجهاز والجوال لوصول Dashboard من أي مكان بدون VPN معقد',
    assignee: 'Dana',
    priority: 'medium',
    status: 'todo',
    tags: ['Setup', 'Network'],
    createdAt: now,
  },
]



